import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <script
          src="https://app.getskiff.com/skiff.js"
          data-app-id="e6df56c1-f69e-47de-af15-a1d6ba97d0e1"
          data-public-key="pk_BP6Wb7bGmBGetroxU9kk0as8QQK2uQB7"
          defer
        ></script>
      </body>
    </html>
  );
}
